### ISSUE TITLE
TouchEvent.TOUCH can work in StarlingMediator?

### ISSUE THREAD

**Issue by hellheaven** [s9tpepper/robotlegs-starling-plugin#3]
hi, I try to make a demo use starling with robotlegs.  but i got an error when i want to add a touchevent in starlingMediator,the view is a starling sprite. code as follow:

eventMap.mapListener(view,TouchEvent.TOUCH,clickHandler);

the error:

 Error: Implicit coercion of a value of type view:AnimationSwitcher to an unrelated type flash.events:IEventDispatcher.

how can i fix this error?

regard.

**Comment by s9tpepper** [comment]
What is the AnimationSwitcher class? Sorry I'm not familiar with what that class is, but the error seems to indicate that the AnimationSwitcher doesn't implement the IEventDispatcher interface, is that class part of Starling? I haven't seen it before.

**Comment by hellheaven** [comment]
Sorry I can't find that demo source now.
but the AnimationSwitcher should  extend starlingMediator of robotlegs.

**Comment by s9tpepper** [comment]
Hm, well, without some code its a little bit hard to try and narrow down what the issue might be.

I think it might be that you're trying to mix Starling objects with the normal Flash/Robotlegs eventMap and they are not compatible. Even though Starling has Events and an EventDispatcher unfortunately they don't implement IEventDispatcher so you can't use them directly with plain Robotlegs eventMap, that's why these plugin classes need to exist in the first place.

If you find or make some sample code I'll take a look at it again.
